# *****************************************************************************
# MQTT Package
#
# Author: Steve Theisen (steve@tyzen9.com)
#         www.tyzen9.com - github.com/tyzen9
#
# Usage:
#   1. Place this package file in a config/packages folder
#   2. Add this to your configuration.yaml:
#      |homeassistant:
#      |  packages: !include_dir_named packages
#   3. Satisfy all dependant "external" entities (see note/examples below)
#   4. Restart Home Assistant
#   5. Drink a cold beverage
#
# Note: Packages require access to entities that are often configured outside
# of this file.  Manytimes, these are from common integrations such as ESPHome,
# Shelly, Zigbee, etc.  These dependant entities are called out in each package
# declaration below.
#
# Some Examples:
#   - ESPHome: https://www.home-assistant.io/integrations/esphome/
#
# *****************************************************************************

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# RESTful Sensors
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sensor:
  # ---------------------------------------------------------------------------
  # This rest call retrieves JSON associated to this container from socket-proxy 
  # and parses the desired json attributes.
  # Hint: post the url into a browser or postman to review the provided JSON
  #
  # Dependencies:
  #  - socket-proxy (see https://github.com/tyzen9/docker-insight)
  #  - secrets.yaml - used to store host names, etc.
  #  - secret_sensor_pkg.yaml - used to convert secret date to sensors 
  #       sensor.secret_host_1_socketproxy_url
  #
  # ---------------------------------------------------------------------------
  - platform: rest
    name: "Host 2 - MQTT - Current Digest"
    unique_id: "host_2_mqtt_current_digest"
    resource_template: "{{ states('sensor.secret_host_2_socketproxy_url') }}/images/eclipse-mosquitto/json"
    scan_interval: 7200
    value_template: "{{ value_json.RepoDigests[0].split('@')[1] }}"
    json_attributes_path: "$.Config"
    json_attributes:
      - Env

template:
  # ---------------------------------------------------------------------------  #
  # This TRIGGERED sensor waches for digest updates in the Diun update handler for 
  # this container and stores the latest digest version.
  # ---------------------------------------------------------------------------  #
  - trigger:
      - trigger: state
        entity_id: sensor.host_2_mqtt_digest_update
    sensor:
      - name: "Host 2 - MQTT - Latest Digest"
        unique_id: "host_2_mqtt_latest_digest"
        state: "{{ states('sensor.host_2_mqtt_digest_update') }}"

  # ---------------------------------------------------------------------------
  # This sensor determines the update status of this container/image and builds
  # a list of attributes useful for displaying on the dashboard
  # ---------------------------------------------------------------------------
  - sensor:
      - name: "Host 2 - MQTT - Update Summary"
        unique_id: "host_2_mqtt_update_summary"
        state: >
          {% from 'macros.jinja' import is_update_available %}
          {{ is_update_available(states('sensor.host_2_mqtt_current_digest'), states('sensor.host_2_mqtt_latest_digest')) }}
        attributes:
          app_name: >
            mqtt
          version: >
            {% set env = state_attr('sensor.host_2_mqtt_current_digest', 'Env') %}
            {% if env %}
              {% set version = env | select('match', '^VERSION=') | list | first | default('') %}
              {{ version.split('=')[1] if version else 'unknown' }}
            {% else %}
              unknown
            {% endif %}
          update_available: >
            {{ this.state }}
          container_state: >
            {{ states('sensor.host_2_mqtt_state') | default('unknown') }}
          status: >
            {{ states('sensor.host_2_mqtt_status') | default('unknown') }}
          health: >
            {{ states('sensor.sensor.host_2_mqtt_health') | default('unknown') }}
          current_digest: >
            {{ states('sensor.host_2_mqtt_current_digest') | default('unknown') }}
          latest_digest: >
            {{ states('sensor.host_2_mqtt_latest_digest') | default('unknown') }}
          release_notes: "https://code.visualstudio.com/updates"
          memory: >
            {{ states('sensor.host_2_mqtt_memory') | default('unknown') }}
          cpu: >
            {{ states('sensor.host_2_mqtt_cpu') | default('unknown') }}
        icon: >
          {{ 'mdi:alert-circle' if this.state == 'yes' else 'mdi:check-circle' }}


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AUTOMATIONS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
automation:
  # ---------------------------------------------------------------------------
  # Generate notification(s) when an update for this container is available
  # ---------------------------------------------------------------------------
  - alias: "Host 2 - MQTT - Update Notification"
    id: host_2_mqtt_update_notification
    description: "Create a dashboard notifications when this container is ready for an update"
    mode: single
    trigger:
      platform: state
      entity_id: sensor.host_2_mqtt_update_summary
      to: 'yes'
    action:
      # Create a dashboard notification
      - service: persistent_notification.create
        data:
          title: "MQTT Update Available"
          message: >
            A new version of MQTT is available (via Docker/Portainer)
          notification_id: host_2_mqtt_update_persistant_notification

  # ---------------------------------------------------------------------------
  # Clear notification(s) when this container has been updated
  # ---------------------------------------------------------------------------
  - alias: "Host 2 - MQTT - Clear Update Notification"
    id: host_2_mqtt_clear_update_notification
    description: "Clear the dashboard notification when this container is updated"
    mode: single
    trigger:
      platform: state
      entity_id: sensor.host_2_mqtt_update_summary
      to: 'no'
    action:
      - service: persistent_notification.dismiss
        data:
          notification_id: host_2_mqtt_update_persistant_notification
