# *****************************************************************************
# Bedroom Main Package
#
# Author: Steve Theisen (steve@tyzen9.com)
#         www.tyzen9.com  -  github.com/tyzen9
#
# Usage:
#   1. Place this package file in a config/packages folder
#   2. Add this to your configuration.yaml:
#      |homeassistant:
#      |  packages: !include_dir_named packages
#   3. Satisfy all dependant "external" entities (see note/examples below)
#   4. Restart Home Assistant
#   5. Drink a cold beverage
#
# Note: Packages require access to entities that are often configured outside
# of this file.  Manytimes, these are from common integrations such as ESPHome,
# Shelly, Zigbee, etc.  These dependant entities are called out in each package
# declaration below.
#
# Some Examples:
#   - UI Scene: Scenes are maintained in the Home Assistant UI
#
# *****************************************************************************

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AUTOMATIONS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
automation:
  # ---------------------------------------------------------------------------
  # Around sunset, turn on some main bedroom accent lighting
  #
  # Dependencies:
  #  - scene.* (UI Scene)
  # ---------------------------------------------------------------------------
  - alias: Bedroom Main - Accent Lighting On
    id: bedroom_main_accent_lighting_on
    description: "Turn on some main bedroom accent lighting in the evening"
    mode: single
    triggers:
      # Around sunset
      - trigger: sun
        event: sunset
    actions:
      # Accent lights in the main bedroom
      - action: scene.turn_on
        target:
          entity_id: scene.mainbedroom_nightstandlight_dusk
        data:
          transition: 2.5

  # ---------------------------------------------------------------------------
  # At a specific time, activate some evening accent lighting
  #
  # Dependencies:
  #  - scene.* (UI Scene)
  # ---------------------------------------------------------------------------
  - alias: Bedroom Main - Evening Accent Lighting On
    id: bedroom_main_evening_accent_lighting_on
    description: "Activate an evening accent lighting scene in the main bedroom"
    mode: single
    triggers:
      # At this time
      - trigger: time
        at: "21:30:00"
    actions:
      # Activate this scene
      - action: scene.turn_on
        target:
          entity_id: scene.mainbedroom_nightstandlight_evening
        data:
          transition: 2.5

  # ---------------------------------------------------------------------------
  # At a specific time, activate nightlight accent lighting
  #
  # Dependencies:
  #  - scene.* (UI Scene)
  # ---------------------------------------------------------------------------
  - alias: Bedroom Main - Nightlight Accent Lighting On
    id: bedroom_main_nightlight_accent_lighting_on
    description: "Activate a nightlight accent lighting scene in the main bedroom"
    mode: single
    triggers:
      # At this time
      - trigger: time
        at: "22:15:00"
    actions:
      # Activate this scene
      - action: scene.turn_on
        target:
          entity_id: scene.mainbedroom_nightstandlight_night
        data:
          transition: 2.5

  # ---------------------------------------------------------------------------
  # Around sunrise, turn on some main bedroom accent lighting
  #
  # Dependencies:
  #  - scene.* (UI Scene)
  # ---------------------------------------------------------------------------
  - alias: Bedroom Main - Acccent Lighting Off
    id: bedroom_main_accent_lighting_off
    description: "Turn off main bedroom accent lighting in the evening"
    mode: single
    triggers:
      # Around sunset
      - trigger: sun
        event: sunrise
        offset: "-02:00:00"
    actions:
      # Turn off the accent lights
      - action: light.turn_off
        target:
          entity_id:
            - light.zl1
