# *****************************************************************************
# Kitchen Package
#
# Author: Steve Theisen (steve@tyzen9.com)
#         www.tyzen9.com  -  github.com/tyzen9
#
# Usage:
#   1. Place this package file in a config/packages folder
#   2. Add this to your configuration.yaml:
#      |homeassistant:
#      |  packages: !include_dir_named packages
#   3. Satisfy all dependant "external" entities (see note/examples below)
#   4. Restart Home Assistant
#   5. Drink a cold beverage
#
# Note: Packages require access to entities that are often configured outside
# of this file.  Manytimes, these are from common integrations such as ESPHome,
# Shelly, Zigbee, etc.  These dependant entities are called out in each package
# declaration below.
#
# Some Examples:
#   - YAML Group: https://www.home-assistant.io/integrations/group/
#
# *****************************************************************************

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AUTOMATIONS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
automation:
  # ---------------------------------------------------------------------------
  # Around sunset, turn on some kitchen accent lighting
  #
  # Dependencies:
  #  - switch.plug_*_switch (INT Zigbee)
  # --------------------------------------------------------------------------- 
  - alias: Kitchen - Accent Lighting On
    id: kitchen_accent_lighting_on
    description: "Turn on some kitchen  accent lighting in the evening"
    mode: single
    trigger:
      # Around sunset
      - platform: sun
        event: sunset
        offset: "01:00:00"
    action:
      # Accent lights in the kitchen
      - action: switch.turn_on
        target:
          entity_id:
            - switch.plug_zp8_switch # Grape Lights
            - switch.plug_zp10       # Dining Room Cabinet


  # ---------------------------------------------------------------------------
  # Around sunrise, turn on some kitchen accent lighting
  #
  # Dependencies:
  #  - switch.plug_*_switch (INT Zigbee)
  # --------------------------------------------------------------------------- 
  - alias: Kitchen - Accent Lighting Off
    id: kitchen_accent_lighting_off
    description: "Turn off kitchen accent lighting in the evening"
    mode: single
    trigger:
      # Around sunset
      - platform: sun
        event: sunrise
        offset: "-02:00:00"
    action:
      # Accent lights in the kitchen
      - action: switch.turn_off
        target:
          entity_id:
            - switch.plug_zp8_switch # Grape Lights
            - switch.plug_zp10       # Dining Room Cabinet
