# *****************************************************************************
# "Snape" PC Package - This is all the functionality that originates from the
#    PC named "snape"
#
# Author: Steve Theisen (steve@tyzen9.com)
#         www.tyzen9.com  -  github.com/tyzen9
#
# Usage:
#   1. Place this package file in a config/packages folder
#   2. Add this to your configuration.yaml:
#      |homeassistant:
#      |  packages: !include_dir_named packages
#   3. Satisfy all dependant "external" entities (see note/examples below)
#   4. Restart Home Assistant
#   5. Drink a cold beverage
#
# Note: Packages require access to entities that are often configured outside
# of this file.  Manytimes, these are from common integrations such as ESPHome,
# Shelly, Zigbee, etc.  These dependant entities are called out in each package
# declaration below.
#
# Some Examples:
#   - ESPHome: https://www.home-assistant.io/integrations/esphome/
#
# Package Depednecies:
#   - wled_utilities_pkg.yaml is needed for the common and custom WLED functions
#
# *****************************************************************************

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SENSORS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
template:
  # ---------------------------------------------------------------------------
  # This binary sensor uses HASS.Agent to determine if the main office PC
  # named Snape is powered on
  #
  # External Package Dependencies:
  #  - sensor.snape_monitorpowerstate (HASS.Agent)
  # ---------------------------------------------------------------------------
  - binary_sensor:
      - name: Snape - Power
        unique_id: snape_power
        state: >
          {{ states('sensor.snape_monitorpowerstate') == "PowerOn" }}
        icon: >
          {% if is_state("binary_sensor.snape_power", "on") %}
            mdi:power-plug-outline
          {% else %}
            mdi:power-plug-off-outline
          {% endif %}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AUTOMATIONS
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
automation:
  # ---------------------------------------------------------------------------
  # When this PC's microphone is active, mute Alexa
  #
  # Dependencies:
  #  - light.dimmer_wd*_dimmer (INT ESPHome)
  # ---------------------------------------------------------------------------
  - alias: PC Snape - Microphone Active Actions
    id: pc_snape_microphone_active_actions
    description: "When the PC's microphone is active, quiet Alexa"
    mode: single
    triggers:
      # When the microphone is active
      - trigger: state
        entity_id: binary_sensor.snape_microphoneactive
        from: "off"
        to: "on"
    actions:
      # Mute the Alexa volume
      - action: media_player.volume_set
        data:
          volume_level: 0.0
        target:
          entity_id:
            - media_player.alexa_office

  # ---------------------------------------------------------------------------
  # When this PC's microphone is active, reset the Alexa volumne.
  #
  # Dependencies:
  #  - light.dimmer_wd*_dimmer (INT ESPHome)
  # ---------------------------------------------------------------------------
  - alias: PC Snape - Microphone Dectivated Actions
    id: ps_snape_microphone_deactivated_actions
    description: "When the PC's microphone is deactivated, reset Alexa volumne"
    mode: single
    triggers:
      # When the microphone is deactivated
      - trigger: state
        entity_id: binary_sensor.snape_microphoneactive
        from: "on"
        to: "off"
    actions:
      # Rerset the Alexa volume
      - action: media_player.volume_set
        data:
          volume_level: 0.5
        target:
          entity_id:
            - media_player.alexa_office

  # ---------------------------------------------------------------------------
  # When this PC's microphone is active, set some lighting for office
  #
  # Dependencies:
  #  - light.dimmer_wd*_dimmer (INT ESPHome)
  # ---------------------------------------------------------------------------
  - alias: PC Snape - Webcam Active Actions
    id: pc_spate_webcam_active_actions
    description: "When the PC's webcam is active, set some lighting"
    mode: single
    triggers:
      # When the microphone is active
      - trigger: state
        entity_id: binary_sensor.snape_webcamactive
        from: "off"
        to: "on"
    actions:
      # Define a new scene based on the current state of these RGBW bulbs
      - action: scene.create
        data:
          scene_id: snape_premeeting_lighting
          snapshot_entities:
            - light.dimmer_wd14_dimmer
            - light.dimmer_wd07_dimmer
      # Activate the meeting active scene
      - action: scene.turn_on
        target:
          entity_id: scene.snape_active_meeting

  # ---------------------------------------------------------------------------
  # When this PC's webcam is deactivated, revert the lighting to the previous
  # configuration.
  #
  # Dependencies:
  #  - light.dimmer_wd*_dimmer (INT ESPHome)
  # ---------------------------------------------------------------------------
  - alias: PC Snape - Webcam Dectivated Actions
    id: pc_snape_webcam_deactivated_actions
    description: "When the PC's webcam is deactivated, reset some lighing"
    mode: single
    triggers:
      # When the microphone is active
      - trigger: state
        entity_id: binary_sensor.snape_webcamactive
        from: "on"
        to: "off"
        for:
          seconds: 15
    actions:
      # Revert to the scene that was saved when the microphone turned on
      - action: scene.turn_on
        target:
          entity_id: scene.snape_premeeting_lighting

  # ---------------------------------------------------------------------------
  # When the PC shuts down, then turn off some accent lighting
  #
  # ---------------------------------------------------------------------------
  - alias: PC Snape - Power Off
    id: pc_snape_power_off
    description: ""
    mode: single
    triggers:
      # When the PC is turned off
      - trigger: state
        entity_id: sensor.snape_monitorpowerstate
        to: "unavailable"
    action:
      - action: script.wled_off
        data:
          wled_hostname: "wled-basement-office.local"

  # ---------------------------------------------------------------------------
  # When the PC turns on, then turn on some accent lighting
  #
  # ---------------------------------------------------------------------------
  - alias: PC Snape - Power On
    id: pc_snape_power_on
    description: ""
    mode: single
    triggers:
      # When the PC is turned off
      - trigger: state
        entity_id: sensor.snape_monitorpowerstate
        to: "PowerOn"
    action:
      # Then turn off some accent lighting
      - action: script.wled_on
        data:
          wled_hostname: "wled-basement-office.local"
